### ISSUE TITLE
User rating on Trade complete

### ISSUE THREAD

**Issue by meditations** [ianleggett/TinanceUI#27]
When a trade is displayed, please show rating stars that can be set for counterparty
Trade data now has (integer) sellerRating & buyerRating fields. (-1=not set) 0-5 = star rating

![image](https://user-images.githubusercontent.com/827175/127607831-1298fcc4-6a56-44c8-8b6b-45afaa7dfcae.png)

Clicking 1 star sets 1 star rating, clicking 2 stars, etc 

Call the new API function  (jwt-data-services) ​/v1​/ratetrade.json (tradeId, rating0-5 )

1. User rating 5 stars

**Comment by laozhu** [comment]
Tested, my request payload (query)

```json
{
 "rating": 3,
 "extraComments": "111111",
 "tradeid": "a8cc7cdf522f44febe42d82cdf818fd9"
}
```

![UI](https://user-images.githubusercontent.com/1212457/127775954-0d7c16b5-be9f-4f1f-867e-3fb70bfc6d1d.png)

**Comment by meditations** [comment]
Can click the button, but nothing happened. @ianleggett Can you check the api calling is going through?

**Comment by laozhu** [comment]
Change `extraComments` to `comments`

**Comment by ianleggett** [comment]
Fields need to be:
{
 "rating": 3,
 "*comment": "111111",                    <----- check carefully
 "tradeid": "a8cc7cdf522f44febe42d82cdf818fd9"
}

**Comment by laozhu** [comment]
After rated success, hide the rate button.

**Comment by meditations** [comment]
private int sellerRating = -1; // -1 not set 0..5
	private String commentAboutSeller;
	private int buyerRating = -1; // -1 not set 0..5
	private String commentAboutBuyer;

**Comment by laozhu** [comment]
```ts
if ((isSeller && sellerRating !== -1) || (isBuyer && buyerRating !== -1)) {
  hide the rate button
}
```

**Comment by ianleggett** [comment]
if (isSeller && buyerRating !== -1) {
  hide the rate button
  display buyerRating stars and comment
}
if (isBuyer && sellerRating !== -1){
 hide the rate button
  display sellerRating stars and comment
}
