### ISSUE TITLE
Add a network badge to top menu showing which network is running

### ISSUE THREAD

**Issue by ianleggett** [ianleggett/TinanceUI#28]
Use /v1/public/getnetworkprofile.json to get the current network name
example result
{"key":"profile","value":"kovan"}

This will display a rounded rectangle button next to (connected status) displaying 'kovan'

**Comment by laozhu** [comment]
Hold on

**Comment by ianleggett** [comment]
please use /v1/public/getnetworkprofile.json on demo.tinance.io for testing
