### ISSUE TITLE
User Rating on Markets page

### ISSUE THREAD

**Issue by ianleggett** [ianleggett/TinanceUI#31]
![image](https://user-images.githubusercontent.com/827175/127610288-499445f1-6ea6-42e6-a279-cbd2e10cb5b5.png)

Listing on markets page can be updated to show new data added to user details:
1. Next to star ratings show how many ratings were given (ratedCount)
2. How many trades done (tradeCount)
3. Total trading volume (tradeVolume)
4. No. of trades this user has cancelled ( tradeCancelCount )
5. Average trade time (aveTradeTime) string

**Comment by ianleggett** [comment]
Next to rating put in brackets the '(' tradeCount ')'

**Comment by laozhu** [comment]
Added fields for market list page @ianleggett without testing, because no data in my list.
