### ISSUE TITLE
Need to display the bank details in trade page for the buyer

### ISSUE THREAD

**Issue by meditations** [ianleggett/TinanceUI#37]

**Comment by ianleggett** [comment]
Example return ,"sellerBankDetails":{"id":13,"payType":{"id":1,"name":"Bank Transfer","enabled":true,"field1name":"Bank name","field2name":"Bank address","field3name":"Swift code","field4name":"Account name","field5name":"Account number"},"field1value":"Test bank","field2value":"1 test drive, test","field3value":"4334413535","field4value":"Test Smith","field5value":"3414116146363623426","usernotes":"","timesUsed":0,"updated":"2021-08-02 13:55:41.982"}

**Comment by meditations** [comment]
<img width="1234" alt="Screen Shot 2021-08-04 at 9 11 11 AM" src="https://user-images.githubusercontent.com/1285857/128097744-f8016aae-2394-490a-9f2a-dd80fc8d11c1.png">

Can you move the details right below this line?
"The seller has deposited crypto, please check the transaction and send Fiat bank funds now"
Bank details

**Comment by laozhu** [comment]
fixed @meditations
