### ISSUE TITLE
Deposit button - better user experience

### ISSUE THREAD

**Issue by ianleggett** [ianleggett/TinanceUI#38]
When deposit button is pressed, we need the circular progress Icon to appear straight away. I have already placed it but it does not work:
TradeList.tsx
![image](https://user-images.githubusercontent.com/827175/127905036-d8e365e8-d4fe-46e8-bc6f-c3e6103c33bf.png)

**Comment by laozhu** [comment]
Add fullscreen depositing overlay

**Comment by ianleggett** [comment]
User experience is not great still !
When button is pushed, make it disabled and put spinner icon on it straight away.
![tinance-deposit-3](https://user-images.githubusercontent.com/827175/128090524-af33ff1b-359b-4f96-a7bd-0a63b32c1346.gif)

**Comment by meditations** [comment]
Need to enable the overlay straightaway

**Comment by laozhu** [comment]
fixed @meditations

**Comment by meditations** [comment]
Overlay works good, but it's slightly lagging behind when the deposit completes, and the buyer's page has been refreshed, but the seller's page is still on overlay. 

Can we disable the overlay as soon as the deposit completes. @laozhu

**Comment by laozhu** [comment]
@meditations  I use `preDepositing` and `depositing` to control the visibility of overlay, If the deposite trade request is done, the depositing state will be set to false automatically, I don't know where is the trigger of the truely "deposit complete", it's not the same as deposite trade request complete?

Where I define depositing state:

<https://github.com/ianleggett/TinanceUI/blob/lin_carnival_integration/tinance-ui/src/pages/TradeList.tsx#L282>

**Comment by ianleggett** [comment]
fixed
