### ISSUE TITLE
Prevent trades when wallet is not connected

### ISSUE THREAD

**Issue by ianleggett** [ianleggett/TinanceUI#6]
Before allowing accept offer, the wallet must be connected.
Default Bank details must also be filled in

**Comment by laozhu** [comment]
What I have done

- add global state walletConnected
- user can trade if walletConnected is true

**Comment by laozhu** [comment]
How to use AppConfig context in src/components/AppConfig.tsx`

1. Initial state of AppConfig context is in `constants/config.ts`, you can add any value here
2. The context have two reducers, update and reset, we use update to change app config
3. Use hooks to consume the global state, there's 3 hooks you can use.

## useAppConfig

If you want to read and write global state both in the same component, useAppConfig is best.

```ts
import { useAppConfig  } from '../components';

const UserWalletPage: React.FC = () => {
  const [config, dispatch] = useAppConfig();

  // Set global state `walletConnected` in app context to true
  const handleWalletConnect = useCallback(() => {
    dispatch({
      type: 'update',
      payload: {
        walletConnected: true,
      },
    });
  }, [dispatch]);

  // Set global state `walletConnected` in app context to false
  const handleWalletDisconnect = useCallback(() => {
    dispatch({
      type: 'update',
      payload: {
        walletConnected: false,
      },
    });
  }, [dispatch]);

  return (...)
}
``` 

## useAppConfigState

If you want to read global state only in the same component, useAppConfigState is best.

```ts
import { useAppConfigState } from '../components';

const MarketListPage: React.FC = () => {
  const { walletConnected } = useAppConfigState();

  const handleTakeOverOffer = useCallback(
    (oid: string) => {
      if (!walletConnected) {
        enqueueSnackbar(t('Please connect user wallet first'), {
          variant: 'warning',
        });
        return;
      }

      if (!creating) {
        setCurrentOrderId(oid);
        setConfirming(true);
      }
    },
    [creating, enqueueSnackbar, t, walletConnected],
  );


  return (
    <Button
      color="secondary"
      variant="outlined"
      onClick={() => handleTakeOverOffer(offer.orderId)}
    >
      {t('Trade')}
    </Button>
  )
}
```

## useAppConfigDispatch

If you want to change global state only in the same component, useAppConfigDispatch is best.

@ianleggett
