### ISSUE TITLE
Add TXN ID and details on trade card

### ISSUE THREAD

**Issue by ianleggett** [ianleggett/TinanceUI#7]
Add transaction IDs in trade detail & 
"depositHash":null,
"completedHash":null
Also add in emails - IAN

**Comment by ianleggett** [comment]
[etherscanlink.pdf](https://github.com/ianleggett/TinanceUI/files/6877309/etherscanlink.pdf)
Added more info for hyperlink detail

**Comment by meditations** [comment]
Add the hyperlink for transaction id according to the etherscanlink.pdf document.

**Comment by meditations** [comment]
Need to open a new window when user clicks the transaction hyperlink.
